# Generated by Django 3.2.6 on 2021-08-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidmedicare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
